apiVersion: v1
kind: Service
metadata:
  name: expose-gs
spec:
  selector:
    job-name: getting-started
  type: LoadBalancer
  ports:
    - port: 1080
      targetPort: 80
  externalIPs:
    - 192.168.2.11
