apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: admin-pseudio-sa-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: admin-pseudo
